src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <description>Device Serial Number</description>
        <inlineHelpText>Device Serial Number</inlineHelpText>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

objects/emailSend__e.object
<CustomObject>
    <description>send an email.</description>
    <fields>
        <fullName>Asset_Id__c</fullName>
        <description>salesforce asset Id, used for getting the contact and asset name.</description>
        <label>Asset Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Type__c</fullName>
        <defaultValue>&apos;Fridge Temperature Warning&apos;</defaultValue>
        <description>type of email</description>
        <label>Email Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>emailSend</label>
    <pluralLabel>emailSends</pluralLabel>
</CustomObject>

classes/SendPlatformEventTest.cls
@isTest(SeeAllData=true)

private class SendPlatformEventTest {
    @isTest static void test() {
        
            
            
            
            emailSend__e  pe = new emailSend__e ();
            pe.Asset_Id__c = [select id from Asset where Serial_Number__c != null limit 1].Id;
            pe.Email_Type__c = 'Fridge Temperature';
            
            // Call method to publish events
            Test.startTest();
            Database.SaveResult sr = EventBus.publish(pe);
            Test.stopTest();

            // Verify SaveResult value - isSuccess should be false
            System.assertEquals(true, sr.isSuccess());
            
            // Log the error message
            for(Database.Error err : sr.getErrors()) {
                System.debug('Error returned: ' +
                             err.getStatusCode() +
                             ' - ' +
                             err.getMessage()+' - '+err.getFields());
            }
    }
}